[theme]
primaryColor = "#6A0DAD"      # Rich royal purple (main accent)
backgroundColor = "#FAFAFA"   # Warm light gray (main background)
secondaryBackgroundColor = "#F4F6F5"  # Slightly deeper gray for sidebars/cards
textColor = "#1A1A1A"         # Deep charcoal for readability

# Optional interactive colors
linkColor = "#7B1FA2"         # Muted deep purple for links/buttons
hoverColor = "#9C27B0"        # Brighter violet for hover/focus states



[server]
headless = true